---
- name: Install Elastic repository
  import_tasks: setup_filebeat_repo.yml

- name: Install InfluxData repository
  import_tasks: setup_telegraf_repo.yml

# Make sure all handlers are executed before running any subsequent roles
- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
