---
- name: add influx key
  rpm_key: 
    state: present 
    key: 'https://repos.influxdata.com/influxdb.key' 
    validate_certs: False
  

- name: add influxdb repo
  template: 
    src: influxdb.repo.j2 
    dest: /etc/yum.repos.d/influxdb.repo