---
- name: restart_telegraf
  service:
    name: "{{ telegraf_aws_service }}"
    enabled: yes
    state: restarted
  when: >
    (ansible_os_family == 'RedHat')
    and (ansible_distribution_version.split(".")[0] == '6')

- name: restart_telegraf_systemd
  systemd:
    name: "{{ telegraf_aws_service }}"
    state: restarted
    enabled: true
    daemon_reload: yes
  when: >
    (ansible_os_family == 'RedHat')
    and (ansible_distribution_version.split(".")[0] == '7')