---

- name: Remove old versions of telegraf
  package:
    name: "{{ telegraf_aws_package }}"
    state: absent
    use: yum
  ignore_errors: yes
  when: telegraf_clean_deploy == true

- name: Install telegraf
  package:
    name: "{{ telegraf_aws_package }}"
    state: present
    update_cache: yes
  notify:
    - restart_telegraf
    - restart_telegraf_systemd
